# Generated by Django 3.0.2 on 2020-02-11 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_existing(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Player = apps.get_model('player', 'Player')
    players = []
    for user in User.objects.all():
        players.append(Player(user=user))
    Player.objects.bulk_create(players)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explore', '0012_news'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explore.Area')),
            ],
        ),
        migrations.RunPython(create_existing),
    ]
