# Generated by Django 3.0.2 on 2020-02-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
