# Generated by Django 3.0.2 on 2020-02-07 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='area_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='explore.Area'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='area_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='explore.Area'),
        ),
    ]
