# Generated by Django 3.0.2 on 2020-02-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_auto_20200207_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creator_only',
            field=models.BooleanField(default=False),
        ),
    ]
