# Generated by Django 3.0.2 on 2020-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
