# Generated by Django 3.0.2 on 2020-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_area_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
